version: "3.4"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1

networks:
  default:
    external:
      name: nginx-proxy
