trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'vikekh/www-server'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: 'latest'